// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `agent_browser_bin_path`, `apply_browser_defaults`, `deskclaw_node_prefix`, `install_agent_browser`, `is_agent_browser_installed`

/// Ensure `agent-browser` is available, installing it if needed.
///
/// Returns the absolute path to the binary, or an error description.
/// This is called during app startup so the browser tool works out-of-box.
Future<String> ensureAgentBrowser() =>
    RustLib.instance.api.crateApiBrowserBootstrapEnsureAgentBrowser();
