// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_browser_defaults`, `find_on_path`

/// Locate the `agent-browser` CLI binary.
///
/// Search order:
/// 1. **Bundled**: `runtimes/agent-browser/agent-browser` (pre-installed at build time)
/// 2. **PATH fallback**: check if `agent-browser` is available on the system PATH
///
/// Returns the absolute path to the binary, or an error description if not found.
Future<String> findAgentBrowser() =>
    RustLib.instance.api.crateApiBrowserBootstrapFindAgentBrowser();
