// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `channel_runtime`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ChannelRuntime`

/// Start all configured channel listeners in the background.
///
/// Reads the current `config_state`, clones it, and spawns
/// `zeroclaw::channels::start_channels(config)`.
///
/// Returns "ok" on success, or "error: …" on failure.
Future<String> startChannelListeners() =>
    RustLib.instance.api.crateApiChannelRuntimeApiStartChannelListeners();

/// Stop all running channel listeners.
///
/// Aborts the background task.  Returns "ok" on success.
Future<String> stopChannelListeners() =>
    RustLib.instance.api.crateApiChannelRuntimeApiStopChannelListeners();

/// Restart channel listeners (stop + start).
///
/// Useful after config changes so the new tokens / enabled flags take effect.
Future<String> restartChannelListeners() =>
    RustLib.instance.api.crateApiChannelRuntimeApiRestartChannelListeners();

/// Check whether channel listeners are currently running.
Future<bool> isChannelListenersRunning() =>
    RustLib.instance.api.crateApiChannelRuntimeApiIsChannelListenersRunning();

/// Get a summary of which channels are currently configured (enabled).
///
/// Returns a list of channel type strings (e.g. `["telegram", "discord"]`).
Future<List<String>> getActiveChannelTypes() =>
    RustLib.instance.api.crateApiChannelRuntimeApiGetActiveChannelTypes();
