// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `copilot_token_dir`, `default_expires_in`, `default_interval`, `fetch_github_username`, `http_client`, `write_file_secure`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AccessTokenResponse`, `ApiEndpoints`, `ApiKeyInfo`, `DeviceCodeResponse`, `GitHubUser`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Start the GitHub OAuth device code flow for Copilot.
/// Returns device flow info including the user_code and verification_uri.
Future<CopilotDeviceFlowInfo> copilotStartDeviceFlow() =>
    RustLib.instance.api.crateApiCopilotApiCopilotStartDeviceFlow();

/// Poll GitHub for authorization completion.
/// Call this repeatedly with the device_code from `copilot_start_device_flow`.
/// Returns a status: "success", "pending", "slow_down", "expired", or "error:..."
Future<CopilotPollResult> copilotPollAuthorization({
  required String deviceCode,
}) => RustLib.instance.api.crateApiCopilotApiCopilotPollAuthorization(
  deviceCode: deviceCode,
);

/// Check if Copilot is already authenticated (has valid cached tokens).
Future<CopilotAuthStatus> copilotCheckStatus() =>
    RustLib.instance.api.crateApiCopilotApiCopilotCheckStatus();

/// Clear all cached Copilot tokens (logout).
Future<String> copilotLogout() =>
    RustLib.instance.api.crateApiCopilotApiCopilotLogout();

/// List available models for Copilot.
/// Copilot doesn't have a model list API, so we return commonly available models.
List<String> copilotAvailableModels() =>
    RustLib.instance.api.crateApiCopilotApiCopilotAvailableModels();

/// Overall Copilot authentication status.
class CopilotAuthStatus {
  /// Whether the user has a valid cached token.
  final bool authenticated;

  /// GitHub username if authenticated.
  final String? username;

  /// Error message if check failed.
  final String? error;

  const CopilotAuthStatus({
    required this.authenticated,
    this.username,
    this.error,
  });

  @override
  int get hashCode =>
      authenticated.hashCode ^ username.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CopilotAuthStatus &&
          runtimeType == other.runtimeType &&
          authenticated == other.authenticated &&
          username == other.username &&
          error == other.error;
}

/// Result of starting the device code flow.
class CopilotDeviceFlowInfo {
  /// The code the user needs to enter at the verification URI.
  final String userCode;

  /// The URL the user should visit (e.g. https://github.com/login/device).
  final String verificationUri;

  /// The device code used for polling (internal, pass to poll function).
  final String deviceCode;

  /// Polling interval in seconds.
  final BigInt interval;

  /// Flow expires after this many seconds.
  final BigInt expiresIn;

  const CopilotDeviceFlowInfo({
    required this.userCode,
    required this.verificationUri,
    required this.deviceCode,
    required this.interval,
    required this.expiresIn,
  });

  @override
  int get hashCode =>
      userCode.hashCode ^
      verificationUri.hashCode ^
      deviceCode.hashCode ^
      interval.hashCode ^
      expiresIn.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CopilotDeviceFlowInfo &&
          runtimeType == other.runtimeType &&
          userCode == other.userCode &&
          verificationUri == other.verificationUri &&
          deviceCode == other.deviceCode &&
          interval == other.interval &&
          expiresIn == other.expiresIn;
}

/// Status of a Copilot authorization poll attempt.
class CopilotPollResult {
  /// "success", "pending", "slow_down", "expired", or "error:[message]"
  final String status;

  /// GitHub username (populated on success).
  final String? username;

  const CopilotPollResult({required this.status, this.username});

  @override
  int get hashCode => status.hashCode ^ username.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CopilotPollResult &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          username == other.username;
}
