// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `from`

/// Check if LLM debug logging is enabled.
bool isLlmDebugEnabled() =>
    RustLib.instance.api.crateApiLlmDebugApiIsLlmDebugEnabled();

/// Enable or disable LLM debug logging.
void setLlmDebugEnabled({required bool enabled}) => RustLib.instance.api
    .crateApiLlmDebugApiSetLlmDebugEnabled(enabled: enabled);

/// Load recent LLM debug entries.
/// Returns entries in reverse chronological order (most recent first).
Future<List<LlmDebugEntryDto>> getLlmDebugEntries({
  required int limit,
  required String sessionFilter,
}) => RustLib.instance.api.crateApiLlmDebugApiGetLlmDebugEntries(
  limit: limit,
  sessionFilter: sessionFilter,
);

/// Get a single LLM debug entry by ID.
Future<LlmDebugEntryDto?> getLlmDebugEntry({required String entryId}) =>
    RustLib.instance.api.crateApiLlmDebugApiGetLlmDebugEntry(entryId: entryId);

/// Clear all LLM debug entries.
Future<String> clearLlmDebugEntries() =>
    RustLib.instance.api.crateApiLlmDebugApiClearLlmDebugEntries();

/// Get the path to the LLM debug log file.
String getLlmDebugLogPath() =>
    RustLib.instance.api.crateApiLlmDebugApiGetLlmDebugLogPath();

/// A single LLM API call debug entry with full request/response details.
class LlmDebugEntryDto {
  final String id;
  final String timestamp;
  final String sessionId;
  final String provider;
  final String model;
  final double temperature;
  final int iteration;
  final List<LlmDebugMessageDto> requestMessages;
  final List<String> toolNames;
  final String responseText;
  final List<LlmDebugToolCallDto> responseToolCalls;
  final BigInt? inputTokens;
  final BigInt? outputTokens;
  final BigInt? durationMs;
  final bool success;
  final String error;
  final String stopReason;

  const LlmDebugEntryDto({
    required this.id,
    required this.timestamp,
    required this.sessionId,
    required this.provider,
    required this.model,
    required this.temperature,
    required this.iteration,
    required this.requestMessages,
    required this.toolNames,
    required this.responseText,
    required this.responseToolCalls,
    this.inputTokens,
    this.outputTokens,
    this.durationMs,
    required this.success,
    required this.error,
    required this.stopReason,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      timestamp.hashCode ^
      sessionId.hashCode ^
      provider.hashCode ^
      model.hashCode ^
      temperature.hashCode ^
      iteration.hashCode ^
      requestMessages.hashCode ^
      toolNames.hashCode ^
      responseText.hashCode ^
      responseToolCalls.hashCode ^
      inputTokens.hashCode ^
      outputTokens.hashCode ^
      durationMs.hashCode ^
      success.hashCode ^
      error.hashCode ^
      stopReason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LlmDebugEntryDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          timestamp == other.timestamp &&
          sessionId == other.sessionId &&
          provider == other.provider &&
          model == other.model &&
          temperature == other.temperature &&
          iteration == other.iteration &&
          requestMessages == other.requestMessages &&
          toolNames == other.toolNames &&
          responseText == other.responseText &&
          responseToolCalls == other.responseToolCalls &&
          inputTokens == other.inputTokens &&
          outputTokens == other.outputTokens &&
          durationMs == other.durationMs &&
          success == other.success &&
          error == other.error &&
          stopReason == other.stopReason;
}

/// A single message in an LLM debug entry.
class LlmDebugMessageDto {
  final String role;
  final String content;
  final int charCount;

  const LlmDebugMessageDto({
    required this.role,
    required this.content,
    required this.charCount,
  });

  @override
  int get hashCode => role.hashCode ^ content.hashCode ^ charCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LlmDebugMessageDto &&
          runtimeType == other.runtimeType &&
          role == other.role &&
          content == other.content &&
          charCount == other.charCount;
}

/// A tool call from an LLM debug response.
class LlmDebugToolCallDto {
  final String name;
  final String arguments;

  const LlmDebugToolCallDto({required this.name, required this.arguments});

  @override
  int get hashCode => name.hashCode ^ arguments.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LlmDebugToolCallDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          arguments == other.arguments;
}
