// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `default_project_status`, `default_project_type`, `persist_store`, `persisted_to_dto`, `persisted_to_summary`, `project_store`, `project_type_to_string`, `status_to_string`, `store_file_path`, `string_to_project_type`, `string_to_status`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `PersistedProject`, `ProjectStore`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

/// Initialize project store — load from disk
Future<String> initProjectStore() =>
    RustLib.instance.api.crateApiProjectApiInitProjectStore();

/// List all projects (summary only)
Future<List<ProjectSummary>> listProjects() =>
    RustLib.instance.api.crateApiProjectApiListProjects();

/// Get full details of a single project
Future<ProjectDto?> getProject({required String projectId}) =>
    RustLib.instance.api.crateApiProjectApiGetProject(projectId: projectId);

/// Create or update a project
Future<String> upsertProject({required ProjectDto project}) =>
    RustLib.instance.api.crateApiProjectApiUpsertProject(project: project);

/// Delete a project (does NOT delete the sessions; only the project container)
Future<String> deleteProject({required String projectId}) =>
    RustLib.instance.api.crateApiProjectApiDeleteProject(projectId: projectId);

/// Add a session to a project
Future<String> addSessionToProject({
  required String projectId,
  required String sessionId,
}) => RustLib.instance.api.crateApiProjectApiAddSessionToProject(
  projectId: projectId,
  sessionId: sessionId,
);

/// Remove a session from a project
Future<String> removeSessionFromProject({
  required String projectId,
  required String sessionId,
}) => RustLib.instance.api.crateApiProjectApiRemoveSessionFromProject(
  projectId: projectId,
  sessionId: sessionId,
);

/// Update project pinned context
Future<String> updateProjectContext({
  required String projectId,
  required String pinnedContext,
}) => RustLib.instance.api.crateApiProjectApiUpdateProjectContext(
  projectId: projectId,
  pinnedContext: pinnedContext,
);

/// Update project status
Future<String> updateProjectStatus({
  required String projectId,
  required ProjectStatus status,
}) => RustLib.instance.api.crateApiProjectApiUpdateProjectStatus(
  projectId: projectId,
  status: status,
);

/// Add a role (agent workspace) to a project
Future<String> addRoleToProject({
  required String projectId,
  required String roleId,
}) => RustLib.instance.api.crateApiProjectApiAddRoleToProject(
  projectId: projectId,
  roleId: roleId,
);

/// Remove a role from a project
Future<String> removeRoleFromProject({
  required String projectId,
  required String roleId,
}) => RustLib.instance.api.crateApiProjectApiRemoveRoleFromProject(
  projectId: projectId,
  roleId: roleId,
);

/// Set the default role for a project
Future<String> setProjectDefaultRole({
  required String projectId,
  required String roleId,
}) => RustLib.instance.api.crateApiProjectApiSetProjectDefaultRole(
  projectId: projectId,
  roleId: roleId,
);

/// Get the project ID that a session belongs to (if any)
Future<String?> getSessionProject({required String sessionId}) => RustLib
    .instance
    .api
    .crateApiProjectApiGetSessionProject(sessionId: sessionId);

/// Get the pinned context for a project (used when creating new sessions
/// within the project to inject historical context)
Future<String> getProjectPinnedContext({required String projectId}) => RustLib
    .instance
    .api
    .crateApiProjectApiGetProjectPinnedContext(projectId: projectId);

/// Full project DTO for Flutter UI
class ProjectDto {
  final String id;
  final String name;
  final String description;
  final String icon;
  final String colorTag;
  final ProjectType projectType;
  final ProjectStatus status;

  /// Bound local filesystem directory (optional)
  final String projectDir;

  /// Cross-session persistent context/memo
  final String pinnedContext;

  /// Bound role (agent workspace) IDs — a project can have multiple roles
  final List<String> roleIds;

  /// Default role ID for new sessions (empty = no default)
  final String defaultRoleId;

  /// Associated session IDs
  final List<String> sessionIds;
  final List<String> tags;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;

  const ProjectDto({
    required this.id,
    required this.name,
    required this.description,
    required this.icon,
    required this.colorTag,
    required this.projectType,
    required this.status,
    required this.projectDir,
    required this.pinnedContext,
    required this.roleIds,
    required this.defaultRoleId,
    required this.sessionIds,
    required this.tags,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      description.hashCode ^
      icon.hashCode ^
      colorTag.hashCode ^
      projectType.hashCode ^
      status.hashCode ^
      projectDir.hashCode ^
      pinnedContext.hashCode ^
      roleIds.hashCode ^
      defaultRoleId.hashCode ^
      sessionIds.hashCode ^
      tags.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          description == other.description &&
          icon == other.icon &&
          colorTag == other.colorTag &&
          projectType == other.projectType &&
          status == other.status &&
          projectDir == other.projectDir &&
          pinnedContext == other.pinnedContext &&
          roleIds == other.roleIds &&
          defaultRoleId == other.defaultRoleId &&
          sessionIds == other.sessionIds &&
          tags == other.tags &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

/// Project status enum exposed to Flutter
enum ProjectStatus { active, paused, archived, completed }

/// Summary for listing projects in sidebar/list
class ProjectSummary {
  final String id;
  final String name;
  final String description;
  final String icon;
  final String colorTag;
  final String projectType;
  final String status;
  final int sessionCount;
  final int roleCount;
  final bool hasProjectDir;
  final List<String> roleIds;
  final String defaultRoleId;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;

  const ProjectSummary({
    required this.id,
    required this.name,
    required this.description,
    required this.icon,
    required this.colorTag,
    required this.projectType,
    required this.status,
    required this.sessionCount,
    required this.roleCount,
    required this.hasProjectDir,
    required this.roleIds,
    required this.defaultRoleId,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      description.hashCode ^
      icon.hashCode ^
      colorTag.hashCode ^
      projectType.hashCode ^
      status.hashCode ^
      sessionCount.hashCode ^
      roleCount.hashCode ^
      hasProjectDir.hashCode ^
      roleIds.hashCode ^
      defaultRoleId.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          description == other.description &&
          icon == other.icon &&
          colorTag == other.colorTag &&
          projectType == other.projectType &&
          status == other.status &&
          sessionCount == other.sessionCount &&
          roleCount == other.roleCount &&
          hasProjectDir == other.hasProjectDir &&
          roleIds == other.roleIds &&
          defaultRoleId == other.defaultRoleId &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

/// Project type enum exposed to Flutter
enum ProjectType {
  /// General-purpose project
  general,

  /// Programming/development project — shows file tree, run commands
  codeProject,

  /// Data processing/analysis — data preview, scheduled execution
  dataProcessing,

  /// Writing/documentation project
  writing,

  /// Automation/scheduled task workflow
  automation,
}
