// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// List all configured model provider profiles
Future<List<ModelProviderProfileDto>> listModelProviderProfiles() =>
    RustLib.instance.api.crateApiProvidersApiListModelProviderProfiles();

/// Create or update a model provider profile. Returns "ok" on success.
Future<String> upsertModelProviderProfile({
  required ModelProviderProfileDto profile,
}) => RustLib.instance.api.crateApiProvidersApiUpsertModelProviderProfile(
  profile: profile,
);

/// Remove a model provider profile. Returns "ok" on success.
Future<String> removeModelProviderProfile({required String id}) =>
    RustLib.instance.api.crateApiProvidersApiRemoveModelProviderProfile(id: id);

/// Switch the active default provider + model at runtime.
/// Used by the chat model selector to quickly switch models.
/// If `provider` matches a model_provider profile ID, applies that profile's configuration.
Future<String> switchActiveModel({
  required String provider,
  required String model,
}) => RustLib.instance.api.crateApiProvidersApiSwitchActiveModel(
  provider: provider,
  model: model,
);

/// Set a provider profile as the default.
/// Updates default_provider, api_url, api_key, and default_model based on the profile.
/// Uses custom:{base_url} format when base_url is provided with OpenAI-compatible endpoints.
Future<String> setDefaultProfile({required String id}) =>
    RustLib.instance.api.crateApiProvidersApiSetDefaultProfile(id: id);

/// Get the current default profile ID.
/// Returns the stored profile ID if set, otherwise returns empty string.
Future<String> getDefaultProfileId() =>
    RustLib.instance.api.crateApiProvidersApiGetDefaultProfileId();

/// Return the count of configured model provider profiles (sync for quick UI display)
int modelProviderProfileCount() =>
    RustLib.instance.api.crateApiProvidersApiModelProviderProfileCount();

/// A configured model provider profile exposed to Flutter UI.
/// Maps to zeroclaw's `[model_providers.<id>]` config section.
class ModelProviderProfileDto {
  /// Unique profile id (config key)
  final String id;

  /// Display name or provider type override (e.g. "openai", "anthropic")
  final String? name;

  /// Base URL for OpenAI-compatible endpoints
  final String? baseUrl;

  /// Wire API protocol ("responses" or "chat_completions")
  final String? wireApi;

  /// Default model for this profile
  final String? defaultModel;

  /// API key (profile-scoped)
  final String? apiKey;

  const ModelProviderProfileDto({
    required this.id,
    this.name,
    this.baseUrl,
    this.wireApi,
    this.defaultModel,
    this.apiKey,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      baseUrl.hashCode ^
      wireApi.hashCode ^
      defaultModel.hashCode ^
      apiKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModelProviderProfileDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          baseUrl == other.baseUrl &&
          wireApi == other.wireApi &&
          defaultModel == other.defaultModel &&
          apiKey == other.apiKey;
}
